# Generated by Django 4.1.5 on 2023-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JiraSentry',
            new_name='Jira_Sentry',
        ),
        migrations.AlterField(
            model_name='issue',
            name='traceback',
            field=models.JSONField(),
        ),
    ]
