# Generated by Django 4.1.5 on 2023-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_jirasentry_jira_sentry_alter_issue_traceback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jira_Sentry',
            new_name='JiraSentryLink',
        ),
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(),
        ),
    ]
