# Generated by Django 4.1.5 on 2023-01-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_key_jira_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='date of receipt',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='sentry_project_name',
        ),
        migrations.RenameField(
            model_name='jirasentrylink',
            old_name='jira project name',
            new_name='jira_project_name',
        ),
        migrations.RenameField(
            model_name='jirasentrylink',
            old_name='sentry project name',
            new_name='sentry_project_name',
        ),
        migrations.RenameField(
            model_name='sentry',
            old_name='last updated',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='jira',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sentry',
            name='name',
        ),
        migrations.AddField(
            model_name='jira',
            name='project_name',
            field=models.CharField(default='DEFAULT', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='sentry',
            name='project_name',
            field=models.CharField(default='DEFAULT', max_length=50, unique=True),
        ),
    ]
