# Generated by Django 4.1.5 on 2023-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_rename_date of receipt_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='traceback',
            field=models.TextField(),
        ),
    ]
