# Generated by Django 4.1.5 on 2023-02-02 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_alter_issue_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira',
            name='linked_with_sentry_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
