# Generated by Django 4.1.5 on 2023-02-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_jira_linked_with_sentry_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jira',
            name='linked_with_sentry_at',
        ),
    ]
