# Generated by Django 4.1.5 on 2023-02-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_remove_jira_linked_with_sentry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira',
            name='uuid',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
