# Generated by Django 4.1.6 on 2023-02-15 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_rename_uuid_jira_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('timeout', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jira',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jira',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jira',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jirasentrylink',
            name='jira_project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='issues.jira'),
        ),
        migrations.AlterField(
            model_name='jirasentrylink',
            name='sentry_project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='issues.sentry'),
        ),
        migrations.AlterField(
            model_name='sentry',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='jira',
            name='auth',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.RESTRICT, to='issues.jiraauth'),
        ),
        migrations.AddField(
            model_name='jira',
            name='connection',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.RESTRICT, to='issues.jiraconnection'),
        ),
    ]
