# Generated by Django 4.1.6 on 2023-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_jiraauth_jiraconnection_jira_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentry',
            name='project_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
