# Generated by Django 4.1.6 on 2023-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_alter_jira_auth_alter_jira_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraconnection',
            name='base_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='jiraconnection',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
